[project]
name = "crossbarv2-kg-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
license = "MIT"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: The MIT License (MIT)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.10",
    "Natural Language :: English",
    "Topic :: Scientific/Engineering :: Bio-Informatics",
]
requires-python = "==3.10.8"
dependencies = [
    "biocypher==0.5.19",
    "bioregistry==0.10.56",
    "h5py==3.10.0",
    "more-itertools==10.2.0",
    "numpy==1.26.4",
    "pandas==2.2.1",
    "pydantic[email]==2.5.2",
    "pypath-omnipath",
    "pysftp>=0.2.9",
    "pyyaml==6.0.1",
    "requests==2.31.0",
    "tqdm==4.66.1",
]

[tool.uv.sources]
pypath-omnipath = { git = "https://github.com/HUBioDataLab/CROssBAR-pypath.git", rev = "master" }
